;; TODO Сделать более общую функцию замены по списку (неважно чего)
;; похоже melpa purty-mode.el может помочь
;; А может быть здесь уместен input-method TeX? Нет, там обратное соответствие.
(setq eab/greek-to-latex '(
                           ("α" "\\alpha")
                           ("A" "\\Alpha")
                           ("β" "\\beta")
                           ("B" "\\Beta")
                           ("γ" "\\gamma")
                           ("Γ" "\\Gamma")
                           ("δ" "\\delta")
                           ("Δ" "\\Delta")
                           ("ε" "\\epsilon")
                           ("ζ" "\\zeta")
                           ("Ζ" "\\Zeta")
                           ("η" "\\eta")
                           ("Η" "\\Eta")
                           ("θ" "\\theta")
                           ("Θ" "\\Theta")
                           ("ι" "\\iota")
                           ("Ι" "\\Iota")
                           ("κ" "\\kappa")
                           ("Κ" "\\Kappa")
                           ("λ" "\\lambda")
                           ("Λ" "\\Lambda")
                           ("μ" "\\mu")
                           ("Μ" "\\Mu")
                           ("ν" "\\nu")
                           ("Ν" "\\Nu")
                           ("ξ" "\\xi")
                           ("π" "\\pi")
                           ("Π" "\\Pi")
                           ("ρ" "\\rho")
                           ("Ρ" "\\Rho")
                           ("σ" "\\sigma")
                           ("Σ" "\\Sigma")
                           ("τ" "\\tau")
                           ("Τ" "\\Tau")
                           ("υ" "\\upsilon")
                           ("ϒ" "\\Upsilon")
                           ("φ" "\\phi")
                           ("Φ" "\\Phi")
                           ("χ" "\\chi")
                           ("X" "\\Chi")
                           ("ψ" "\\psi")
                           ("Ψ" "\\Psi")
                           ("ω" "\\omega")
                           ("Ω" "\\Omega")
                           ))

(defun eab/fast-replace-in-region (from to beg end)
  (perform-replace from to nil nil nil nil nil beg end))

(defun eab/greek-to-latex-in-region ()
  (interactive)
  (let ((beg (region-beginning))
        (end (region-end)))
    (mapcar (lambda (x)
	       (save-excursion
		 (eab/fast-replace-in-region (car x) (cadr x) beg end)))
	    eab/greek-to-latex)))

(provide 'eab-greek-to-latex)
